/************************************************************

program:      Connect 4.

file:         AlphaBetaTree.h

function:

description:  represents the interface of the class AlphaBetaTree

author:       Mohammed Safwat (MS)

environment:  borland c++ builder 1.0, windows 98 second edition
              borland c++ builder 6, windows98 second edition

notes:        This is a project program.

revisions:    1.00  28/12/2003 (MS) starting construction
			  1.01	2/2/2004   (MS) adding some using declarations
              1.02	9/2/2004   (MS) separating the class State from the
              class AlphaBetaTree
              1.03  13/2/2004  (MS) changing the method ApplyAlphaBeta to
              a non-constant method
              1.04  7/3/2004   (MS) adding a destuctor and a Destroy
              method

************************************************************/
//---------------------------------------------------------------------------
#ifndef AlphaBetaTreeH
#define AlphaBetaTreeH
#include "State.h"
class AlphaBetaTree
   {
    public:
    AlphaBetaTree(const unsigned char MaxLevel,
    const vector< TileColumn >& RootState);
    ~AlphaBetaTree();
    void ApplyAlphaBeta(bool& goal, unsigned char& NextStep,
    const player beginner);
    static const unsigned char ThresholdLevel;// The threshold level is
    // the level above which generated states may be duplicated(i.e.
    // produced by more than one parent).
    private:
    void Destroy(State* const CurrentState,
    const unsigned char CurrentLevel);
    const unsigned char ItsMaxLevel;
    const auto_ptr< State > ItsRoot;
    list< State > ItsOpenStates;// to store those states whose level is
    // above the threshold level since they can be generated by more than
    // one parent
   };
//---------------------------------------------------------------------------
#endif
